CREATE TABLE IF NOT EXISTS Employee (
id SERIAL PRIMARY KEY,
Name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Department (
Name VARCHAR(100) PRIMARY KEY,
Supervisor INTEGER REFERENCES Employee(id)
);

ALTER TABLE Employee 
ADD COLUMN Department VARCHAR(100) REFERENCES Department(Name);